### ISSUE TITLE
DEEPSLATE not autocompleted in vscode

### ISSUE THREAD

**Issue by LoneDev6** [ItemsAdder/ia-vscode#12]
```yml
info:
  namespace: minerals_pack
  enabled: true
worlds_populators:
  jade_ore_deepslate:
    block: minerals_pack:jade_ore_deesplate
    worlds:
    - world
    replaceable_blocks:
    - DEEPSLATE
    chunk_chance: 100
    max_height: 0
    min_height: -50
    vein_blocks: 6
    chunk_veins: 1
```
