### ISSUE TITLE
use_mmoitem_displayname wrong type "string"

### ISSUE THREAD

**Issue by LoneDev6** [ItemsAdder/ia-vscode#7]
![image](https://user-images.githubusercontent.com/27242001/236805379-f30e4c0d-30a4-4fc8-93ff-303593b3ff58.png)

Example:
```yml
info:
  namespace: equipments
items:
  stone_sword:
    display_name: Stone Sword
    mmoitem:
      type: SWORD
      id: STONE_SWORD
      use_mmoitem_displayname: true
    resource:
      material: STONE_SWORD
      generate: true
      textures:
        - item/stone_sword
      model_id: 3125002
    durability:
      max_custom_durability: 144
```
